global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:3001"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:3002"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:3003"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "shipping-service"
    static_configs:
      - targets: ["shipping-service:3004"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:3005"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:9187"]
    metrics_path: "/metrics"
    scrape_interval: 30s
